package com.example.order.core

import com.example.order.app.domain.model.ListItem
import com.example.order.datasource.Server.ServerResponseData

object GlobalConstAndVars {
    const val FIRST_INDEX_OF_SECOND_CURRENCY=3
    const val FIRST_INDEX_OF_CROSSCOUSE=6

    const val DEFAULT_VALUE: String = "0"
    var PAIRS_lIST=""
    var listItemFromDb:List<ListItem> = mutableListOf()
    var LIST_KEY: String = DEFAULT_VALUE
    var count: Int = 0
    var KEY_FOR_INFLATE_MAIN_LIST = 0
    var LIST_OF_CHOSEN_ITEMS: MutableList<ListItem> = mutableListOf()
    var DATABASE1C_NAME: String = "Database1C.db"
    /*const val STEP_FOR_WORK_LIST=0.01*///не удалять - может понадобиться
    /*const val NUMBERS_OF_VALUES_FOR_WORK_LIST=3000*///не удалять - может понадобиться
    const val STEP_FOR_WORKED_HOURS=1.0
    const val NUMBERS_OF_VALUES_FOR_WORKED_HOURS=50
    val DEFAULT_lIST= listOf(ListItem("","","",""))
    var DATE_OF_ORDER=""
    var GLOBAL_LIST= DEFAULT_lIST
    var LIST_OF_ITEMS_FOR_FIRST_AND_SECOND_SCREENS:List<ListItem> = mutableListOf()
    const val DEFAULT_VALUE_FOR_GENERATED_LIST="0"
    var LIST_OF_FINISHED_ORDERS = listOf<ServerResponseData>()
    const val MARKER_OF_FINISHED_ORDER="1"
    var WORKED_OUT:String=""
    var SWITCH_FOR_ORDERS_LIST=0
    val countriesList = listOf(
        ListItem("MGA","Мадагаскар","","mg"),
        ListItem("AFN","Афганистан","","af"),
        ListItem("PAB","Панама","","pa"),
        ListItem("THB","Таиланд","","th"),
        ListItem("VEF","Венесуэла","","ve"),
        ListItem("BOB","Боливия","","bo"),
        ListItem("ETB","Эфиопия","","et"),
        ListItem("VUV","Вануату","","vu"),
        ListItem("KPW","Северная Корея","","kp"),
        ListItem("KRW","Южная Корея","","kr"),
        ListItem("UAH","Украина","","ua"),
        ListItem("PYG","Парагвай","","py"),
        ListItem("ANG","Нидерландские Антильские острова","","0"),
        ListItem("HTG","Гаити","","ht"),
        ListItem("GMD","Гамбия","","gm"),
        ListItem("MKD","Северная Македония","","mk"),
        ListItem("DZD","Алжир","","dz"),
        ListItem("BHD","Бахрейн","","bh"),
        ListItem("JOD","Иордания","","jo"),
        ListItem("IQD","Ирак","","iq"),
        ListItem("KWD","Кувейт","","kw"),
        ListItem("LYD","Ливия","","ly"),
        ListItem("RSD","Сербия","","rs"),
        ListItem("TND","Тунис","","tn"),
        ListItem("MAD","Марокко","","ma"),
        ListItem("AED","Объединённые Арабские Эмираты","","0"),
        ListItem("STN","Сан-Томе и Принсипи","","st"),
        ListItem("AUD","Австралия","","au"),
        ListItem("BSD","Багамы","","0"),
        ListItem("BBD","Барбадос","","bb"),
        ListItem("BZD","Белиз","","bz"),
        ListItem("BMD","Бермудские острова","","bm"),
        ListItem("BND","Бруней","","bn"),
        ListItem("XCD","Ангилья","","0"),
        ListItem("GYD","Гайана","","gy"),
        ListItem("HKD","Гонконг","","hk"),
        ListItem("ZWD","Зимбабве","","zw"),
        ListItem("KYD","0","","0"),
        ListItem("CAD","Канада","","ca"),
        ListItem("LRD","Либерия","","lr"),
        ListItem("NAD","Намибия","","na"),
        ListItem("NZD","Новая Зеландия","","nz"),
        ListItem("SGD","Сингапур","","sg"),
        ListItem("SBD","Соломоновы Острова","","sb"),
        ListItem("USD","США","","us"),
        ListItem("SRD","Суринам","","sr"),
        ListItem("TWD","Тайвань","","tw"),
        ListItem("TTD","Тринидад и Тобаго","","tt"),
        ListItem("FJD","Фиджи","","fj"),
        ListItem("JMD","Ямайка","","jm"),
        ListItem("VND","Вьетнам","","vn"),
        ListItem("AMD","Армения","","am"),
        ListItem("EUR","СтраныЕврозоны","","eu"),
        ListItem("PLN","Польша","","pl"),
        ListItem("JPY","Япония","","jp"),
        ListItem("AOA","Ангола","","ao"),
        ListItem("ZMK","Замбия","","zm"),
        ListItem("MWK","Малави","","mw"),
        ListItem("GTQ","Гватемала","","gt"),
        ListItem("PGK","Папуа — Новая Гвинея","","0"),
        ListItem("LAK","Лаос","","la"),
        ListItem("CRC","Коста-Рика","","cr"),
        ListItem("NIO","Никарагуа","","ni"),
        ListItem("DKK","Дания","","dk"),
        ListItem("ISK","Исландия","","is"),
        ListItem("NOK","Норвегия","","no"),
        ListItem("—","Фарерские острова","","fo"),
        ListItem("CZK","Чехия","","cz"),
        ListItem("SEK","Швеция","","se"),
        ListItem("HRK","Хорватия","","hr"),
        ListItem("MMK","Мьянма","","мм"),
        ListItem("GEL","Грузия","","ge"),
        ListItem("LVL","Латвия","","lv"),
        ListItem("BGN","Болгария","","bg"),
        ListItem("MDL","Молдавия","","0"),
        ListItem("RON","Румыния","","ro"),
        ListItem("ALL","Албания","","al"),
        ListItem("HNL","Гондурас","","hn"),
        ListItem("SLL","Сьерра-Леоне","","sl"),
        ListItem("SZL","Свазиленд","","0"),
        ListItem("TRY","Турция","","tr"),
        ListItem("LTL","Литва","","lt"),
        ListItem("LSL","Лесото","","ls"),
        ListItem("AZN","Азербайджан","","az"),
        ListItem("TMТ","Туркмения","","0"),
        ListItem("BAM","Босния и Герцеговина","","ba"),
        ListItem("MZN","Мозамбик","","mz"),
        ListItem("NGN","Нигерия","","ng"),
        ListItem("ERN","Эритрея","","er"),
        ListItem("BTN","Бутан","","bt"),
        ListItem("TOP","Тонга","","to"),
        ListItem("MOP","Макао","","mo"),
        ListItem("ARS","Аргентина","","ar"),
        ListItem("DOP","Доминиканская республика","","0"),
        ListItem("COP","Колумбия","","co"),
        ListItem("CUP","Куба","","cu"),
        ListItem("MXN","Мексика","","mx"),
        ListItem("UYU","Уругвай","","uy"),
        ListItem("PHP","Филиппины","","ph"),
        ListItem("CLP","Чили","","cl"),
        ListItem("BWP","Ботсвана","","bw"),
        ListItem("BRL","Бразилия","","br"),
        ListItem("IRR","Иран","","ir"),
        ListItem("YER","Йемен","","ye"),
        ListItem("QAR","Катар","","qa"),
        ListItem("OMR","Оман","","om"),
        ListItem("KHR","Камбоджа","","kh"),
        ListItem("MYR","Малайзия","","my"),
        ListItem("SAR","Саудовская Аравия","","sa"),
        ListItem("BYN","Белоруссия","","by"),
        ListItem("RUB","Россия","","ru"),
        ListItem("INR","Индия","","in"),
        ListItem("IDR","Индонезия","","id"),
        ListItem("MUR","Маврикий","","mu"),
        ListItem("NPR","Непал","","np"),
        ListItem("PKR","Пакистан","","pk"),
        ListItem("SCR","Сейшелы","","0"),
        ListItem("LKR","Шри-Ланка","","lk"),
        ListItem("MVR","Мальдивы","","mv"),
        ListItem("ZAR","ЮАР","","0"),
        ListItem("GHS","Гана","","gh"),
        ListItem("PEN","Перу","","pe"),
        ListItem("KGS","Киргизия","",""),
        ListItem("TJS","Таджикистан","","tj"),
        ListItem("UZS","Узбекистан","","uz"),
        ListItem("BDT","Бангладеш","","bd"),
        ListItem("WST","Самоа","","ws"),
        ListItem("KZT","Казахстан","","kz"),
        ListItem("MNT","Монголия","","mn"),
        ListItem("MRO","Мавритания","","mr"),
        ListItem("AWG","Аруба","","aw"),
        ListItem("HUF","Венгрия","","hu"),
        ListItem("BIF","Бурунди","","bi"),
        ListItem("GNF","Гвинея","","gn"),
        ListItem("DJF","Джибути","","dj"),
        ListItem("KMF","Коморы","",""),
        ListItem("CDF","Демократическая Республика Конго","","0"),
        ListItem("RWF","Руанда","","rw"),
        ListItem("CHF","Швейцария","","ch"),
        ListItem("XPF","0","","0"),
        ListItem("XOF","Бенин","","0"),
        ListItem("XAF","Габон","","0"),
        ListItem("GBP","Великобритания","","gb"),
        ListItem("GIP","Гибралтар","","gi"),
        ListItem("EGP","Египет","","eg"),
        ListItem("LBP","Ливан","","lb"),
        ListItem("SHP","Остров Святой Елены","","sh"),
        ListItem("SYP","Сирия","","sy"),
        ListItem("SDG","Судан","","sd"),
        ListItem("FKP","Фолклендские острова","","fk"),
        ListItem("ILS","Израиль","","il"),
        ListItem("KES","Кения","","ke"),
        ListItem("SOS","Сомали","","so"),
        ListItem("TZS","Танзания","","tz"),
        ListItem("UGX","Уганда","","ug"),
        ListItem("CVE","Кабо-Верде","","cv"),
        ListItem("CNY","Китай","","cn"),
        ListItem("BCH","Биткойн Cash","","bch"),
        ListItem("BTC","Ripple","","bch"),
        ListItem("XRP","Криптовалюта","","bch"),
        ListItem("AED","ОАЭ","","ae"),
        ListItem("KGS","Киргизия","","kg")


    )


}